import turtle import random #screen set up wn = turtle.Screen() wn.title("Simple Maze Game") wn.bgcolor("black") wn.setup(width=600, height=600) wn.tracer(0) #walls of the maze being defined and what they look like in turtle rows = 10 cols = 10 cell_size = 40 pen = turtle.Turtle() pen.shape("square") pen.color("white") pen.penup() pen.speed(0) #setting up the player player = turtle.Turtle() player.shape("circle") player.color("cyan") player.penup() player.speed(0) #making the maze grid with randomized blocks on grid and checking to see if its solvable #making the maze grid with randomized blocks on grid and checking to see if its solvable maze = [[1 for _ in range(cols)] for _ in range(rows)] def carve_passages_from(y, x): directions = [(0, 2), (0, -2), (2, 0), (-2, 0)] random.shuffle(directions) for dy, dx in directions: ny, nx = y + dy, x + dx if 0 < ny < rows - 1 and 0 < nx < cols - 1 and maze[ny][nx] == 1: maze[ny - dy // 2][nx - dx // 2] = 0 maze[ny][nx] = 0 carve_passages_from(ny, nx) carve_passages_from(1, 1) def move(dx, dy): new_x = player.xcor() + dx * cell_size new_y = player.ycor() + dy * cell_size grid_x = int((new_x + cols * cell_size / 2) // cell_size) grid_y = int((rows * cell_size / 2 - new_y) // cell_size) if 0 <= grid_x < cols and 0 <= grid_y < rows and maze[grid_y][grid_x] == 0: player.goto(new_x, new_y) if (grid_y, grid_x) == (rows - 2, cols - 2): win_text = turtle.Turtle() win_text.hideturtle() win_text.color("yellow") win_text.write(" You reached the end!! ", align="center", font=("Arial", 16, "bold")) def up(): move(0, 1) def down(): move(0, -1) def left(): move(-1, 0) def right(): move(1, 0) wn.listen() wn.onkeypress(up, "w") wn.onkeypress(down, "s") wn.onkeypress(left, "a") wn.onkeypress(right, "d") start_x = -cols * cell_size / 2 + cell_size start_y = rows * cell_size / 2 - 2 * cell_size player.goto(start_x, start_y) draw_maze() while True: wn.update()


















































































































